export const getPrompt = [
    "A futuristic cityscape with flying cars and neon lights, in a modern style",
"A sleek, high-tech home interior with smart gadgets and holographic displays",
"A bustling futuristic marketplace with diverse alien species and advanced technology",
"A vertical garden skyscraper with integrated living spaces and green energy solutions",
"A futuristic park with robotic animals and interactive art installations",
"A modern fashion show featuring high-tech, glowing clothing and accessories",
"A futuristic train station with magnetic levitation trains and digital billboards",
"A serene, high-tech zen garden with robotic gardeners and holographic koi fish",
"A futuristic sports arena with advanced VR technology and augmented reality displays",
"A modern, eco-friendly urban farm with robotic farmers and vertical crop beds",
"A futuristic underwater city with advanced architecture and marine life integration",
"A modern, high-tech kitchen with robotic chefs and AI-controlled appliances",
"A futuristic amusement park with advanced rides and holographic attractions",
"A sleek, modern office space with advanced workstations and virtual meeting rooms",
"A futuristic, autonomous vehicle in a modern urban setting",
"A high-tech gym with robotic personal trainers and augmented reality workouts",
"A futuristic library with interactive, holographic books and AI librarians",
"A modern home with integrated AI assistants and advanced home automation",
"A futuristic spaceport with sleek, advanced spacecraft and alien travelers",
"A high-tech medical facility with robotic surgeons and advanced diagnostic tools",
"A futuristic concert hall with holographic performers and immersive sound systems",
"A modern, high-tech school with interactive learning environments and AI teachers",
"A futuristic beach resort with advanced water sports and robotic lifeguards",
"A sleek, modern skyscraper with integrated green energy solutions and smart windows",
"A futuristic shopping mall with robotic store assistants and virtual fitting rooms",
"A high-tech, modern art gallery with interactive exhibits and holographic art",
"A futuristic airport with autonomous luggage handlers and advanced security systems",
"A modern, high-tech hospital room with advanced medical equipment and virtual care",
"A futuristic train with panoramic windows and advanced passenger amenities",
"A sleek, modern space station with advanced living quarters and research labs",
"A futuristic zoo with robotic animal caretakers and interactive exhibits",
"A modern, high-tech concert with holographic performers and immersive sound",
"A futuristic vertical farm with advanced hydroponic systems and robotic farmers",
"A sleek, modern apartment with integrated AI and advanced home automation",
"A futuristic theme park with advanced rides and holographic attractions",
"A high-tech, modern office with virtual workspaces and advanced collaboration tools",
"A futuristic cruise ship with advanced amenities and interactive entertainment",
"A modern, high-tech library with interactive, holographic books and AI librarians",
"A futuristic sports car in a sleek, modern urban setting",
"A high-tech, modern restaurant with robotic chefs and AI waitstaff",
"A futuristic city with advanced public transportation and smart infrastructure",
"A modern, high-tech gym with robotic personal trainers and augmented reality workouts",
"A futuristic research lab with advanced equipment and holographic displays",
"A sleek, modern hospital with advanced medical technology and virtual care",
"A futuristic space colony with advanced architecture and sustainable living",
"A high-tech, modern shopping center with interactive stores and virtual fitting rooms",
"A futuristic luxury hotel with advanced amenities and robotic concierge",
"A modern, high-tech conference center with advanced collaboration tools and virtual meetings",
"A futuristic ocean city with advanced underwater architecture and marine life integration",
"A sleek, modern transportation hub with autonomous vehicles and smart infrastructure",

"A futuristic cityscape at night with glowing skyscrapers and flying drones",
"A high-tech, modern living room with a virtual reality entertainment system",
"A futuristic garden with robotic plant caretakers and holographic flowers",
"A sleek, modern bedroom with smart home integration and AI-controlled lighting",
"A futuristic workspace with advanced holographic displays and virtual assistants",
"A high-tech, modern kitchen with robotic chefs and voice-activated appliances",
"A futuristic sports arena with augmented reality training facilities and smart gear",
"A sleek, modern bathroom with advanced water-saving technology and smart mirrors",
"A futuristic street market with robotic vendors and interactive product displays",
"A high-tech, modern school with interactive learning environments and AI teachers",
"A futuristic library with holographic books and robotic librarians",
"A sleek, modern office with advanced collaboration tools and virtual workspaces",
"A futuristic city park with robotic gardeners and holographic art installations",
"A high-tech, modern hospital with advanced medical technology and virtual care",
"A futuristic amusement park with holographic attractions and advanced rides",
"A sleek, modern transportation hub with autonomous vehicles and smart infrastructure",
"A futuristic research lab with advanced equipment and holographic displays",
"A high-tech, modern concert hall with immersive sound systems and holographic performers",
"A futuristic underwater city with advanced architecture and marine life integration",
"A sleek, modern home with integrated AI and advanced home automation",
"A futuristic shopping mall with robotic store assistants and virtual fitting rooms",
"A high-tech, modern library with interactive, holographic books and AI librarians",
"A futuristic sports car in a sleek, modern urban setting",
"A sleek, modern hospital with advanced medical technology and virtual care",
"A futuristic space colony with advanced architecture and sustainable living",
"A high-tech, modern shopping center with interactive stores and virtual fitting rooms",
"A futuristic luxury hotel with advanced amenities and robotic concierge",
"A sleek, modern conference center with advanced collaboration tools and virtual meetings",
"A futuristic ocean city with advanced underwater architecture and marine life integration",
"A high-tech, modern gym with robotic personal trainers and augmented reality workouts",
"A futuristic city with advanced public transportation and smart infrastructure",
"A sleek, modern bedroom with smart home integration and AI-controlled lighting",
"A futuristic garden with robotic plant caretakers and holographic flowers",
"A high-tech, modern living room with a virtual reality entertainment system",
"A futuristic workspace with advanced holographic displays and virtual assistants",
"A sleek, modern bathroom with advanced water-saving technology and smart mirrors",
"A futuristic street market with robotic vendors and interactive product displays",
"A high-tech, modern school with interactive learning environments and AI teachers",
"A futuristic library with holographic books and robotic librarians",
"A sleek, modern office with advanced collaboration tools and virtual workspaces",
"A futuristic city park with robotic gardeners and holographic art installations",
"A high-tech, modern hospital with advanced medical technology and virtual care",
"A futuristic amusement park with holographic attractions and advanced rides",
"A sleek, modern transportation hub with autonomous vehicles and smart infrastructure",
"A futuristic research lab with advanced equipment and holographic displays",
"A high-tech, modern concert hall with immersive sound systems and holographic performers",
"A futuristic underwater city with advanced architecture and marine life integration",
"A sleek, modern home with integrated AI and advanced home automation",
"A futuristic shopping mall with robotic store assistants and virtual fitting rooms",
"A high-tech, modern library with interactive, holographic books and AI librarians"
]