import React, { useEffect, useState } from 'react';
import Loading from '../Shared/Loading';
import FormField from '../Shared/FormField';
import Card from '../Shared/Card';
import axiosSecure from '../CustomHook/useAxiosSecure';


const RenderCards = ({data, title}) =>{
    if(data?.length > 0){
        return data.map((post)=> <Card key={post._id} {...post}></Card>)
    }
    else{
        return <Loading></Loading>
    }
}

const Home = () => {
    const [loading, setLoading] = useState(false);
    const [searchText, setSearchText] = useState('');
    const [allPosts, setAllPosts] = useState([]);
    const [searchResults, setSearchResults] = useState(null);

    useEffect(()=>{
      const fetchPosts = async() =>{
        setLoading(true);

        try{

            axiosSecure.get('/generate')
            .then(res => {
                setAllPosts(res.data.data)
            })
            .catch(error => {
                console.log(error);
            });
           
        }
        catch(error){

        }
        finally{
            setLoading(false);
        }
      }
      fetchPosts();
    },[])


    const handleChange = (e) =>{
        setSearchText(e.target.value);

            setTimeout(()=>{
                const searchResults = allPosts.filter((item)=> item.name.toLowerCase().includes(searchText.toLowerCase()) || item.prompt.toLowerCase().includes(searchText.toLowerCase()));
    
                setSearchResults(searchResults);
            }, 500);
        
    }

    return (
        <main className='relative'>
 
            <section className='max-w-5xl md:mx-auto mx-10 relative'>
                
                <div>
                    <h1 className='font-bold heading md:text-[32px] text-[28px]'>The Community Showcase</h1>
                    <p className='para text-[14px] md:text-lg'>Browser through a collection of imaginative and visually stunning images generated by OpenAi Dall-e.</p>
                </div>

                <div className='mt-10'>
                    {/* form field  */}
                    <FormField
                        labelName={"Search Posts"}
                        type={'text'}
                        name={'search'}
                        handleChange={handleChange}
                        placeholder={"Search Ai Generated Images"}
                    />
                    
                </div>

                <div>
                    {
                        loading ? <Loading></Loading> : (
                            <>
                            {
                                searchText && <h2 className='para md:text-md text-[14px] mb-3'>Showing results for <span className='heading font-medium'>{searchText}</span></h2>
                            }

                            <div className='lg:columns-3 md:columns-2 xs:columns-1 text-md my-5'>
                                {
                                    searchText ? (
                                        <RenderCards data={searchResults} title="No search results found"/>
                                    ) : (
                                        <RenderCards data={allPosts} title={"No posts found"} />
                                    )
                                }
                            </div>
                            </>
                        )
                    }
                    
                </div>
            </section>
        </main>
    );
};

export default Home;